@ECHO OFF
 IF EXIST *.tmp DEL *.tmp >NUL
 IF EXIST *.bak DEL *.bak >NUL
 IF EXIST *.cdx DEL *.cdx >NUL
 IF EXIST *.vue DEL *.vue >NUL
 IF EXIST *.spr DEL *.spr >NUL
 IF EXIST *.spx DEL *.spx >NUL
 IF EXIST *.mpr DEL *.mpr >NUL
 IF EXIST *.mpx DEL *.mpx >NUL
 IF EXIST *.qpx DEL *.qpx >NUL
 IF EXIST *.prg DEL *.prg >NUL
 IF EXIST *.fxp DEL *.fxp >NUL
 IF EXIST *.mn? DEL *.mn? >NUL
 IF EXIST *.sc? DEL *.sc? >NUL
 IF EXIST *.pj? DEL *.pj? >NUL
 IF EXIST *.fr? DEL *.fr? >NUL
